spring:
  datasource:
    url: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
    username: ${PGUSER}
    password: ${PGPASSWORD}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
# --- NOVAS CONFIGURAÇÕES PARA O FRONTEND ---
  web:
    resources:
      static-locations: classpath:/static/  # Pasta onde o frontend será servido
  mvc:
    static-path-pattern: /**                # Garante que todas as rotas não-API caiam no frontend
